import type { Metadata } from "next";
import BottomNav from './components/BottomNav'
import Header from './components/Header'
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={` antialiased`}
        >

          <Header />
          {children}
          <BottomNav />
        </body>
      </html>

    </ClerkProvider>

  );
}
