import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DarkModeToggle from "@/components/ui/Darkmode-button";
import BacktoHome from "@/components/ui/BacktoHome";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="z-10 absolute top-5 sm:top-3 right-5 flex">
        <DarkModeToggle />
        </div>
       <div className="bg-[#023047] dark:bg-[#219ebc]"> 
        {children}
        </div>
        <div className="fixed bottom-5 right-5">
          <BacktoHome />
        </div>
      </body>
    </html>
  );
}
